name: Auto Add Files to Contributions

on:
  pull_request:
    types:
      - opened

permissions:
  contents: write

jobs:
  auto-add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move all files to contributions folder
        run: |
          mkdir -p contributions
          mv * contributions/ || true

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add contributions/
          git commit -m "Automatically move files to contributions folder" || true
          git push

      - name: Auto merge pull request
        uses: peter-evans/auto-merge-action@v3
        with:
          merge-method: merge
